### PR TITLE
More formatting

### PR DESCRIPTION
**Pull request by Samisafool**
This time, don't merge yet! I will come tomorrow and do some more stuff, namely complete the TODOs

### CODE REVIEW

**Comment by CuBeRJAN** [comment]
alright

**Comment by Samisafool** [comment]
Hey @CuBeRJAN I've done quite a bit of work, do you mind testing this branch? It should work

**Comment by CuBeRJAN** [comment]
alright I'll test it

**Comment by Samisafool** [comment]
OHH I'm stupid

**Comment by Samisafool** [comment]
There's still more stuff to do, like deduplication the addition of flatpak, etc, but you can merge now.

**Comment by CuBeRJAN** [comment]
I'll do some more testing and if it works I'll merge

**Comment by Samisafool** [comment]
Oh and I forgot to add that "a" flag, thanks

**Comment by CuBeRJAN** [comment]
seems good now!

**Pull request merged**
